### ISSUE TITLE
Example uses <http://schema.org/Document>, which doesn’t exist

### ISSUE THREAD

**Issue by unor** [rdfa/rdfa-website#53]
The prefilled example markup on https://rdfa.info/play/ is:

```
<span vocab="http://schema.org/" typeof="Document">
   <a property="url" href="http://www.w3.org/TR/rdfa-primer/">
      <span property="title">RDFa 1.1 Primer</span></a>.
</span>
```

But Schema.org doesn’t have a `Document` type ([gives error 404](http://schema.org/Document)). 

It should probably be a [`TechArticle`](http://schema.org/TechArticle) instead:

> A technical article - Example: How-to (task) topics, step-by-step, procedural troubleshooting, specifications, etc.

**Comment by niklasl** [comment]
Thanks for the catch @unor!

**Comment by gkellogg** [comment]
This is likely because we switched from FOAF to schema.

**Comment by niklasl** [comment]
Quite likely. You just prompted me to look closer, and also change title to name. Since <http://schema.org/title> is "The title of the job" whereas <http://schema.org/name> is "The name of the item". (The latter is used for all kinds of names in schema.org, including titles of books, as seen in examples of <http://schema.org/Book>.)
